name: Deploy to Production

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.ACCESS_TOKEN }}
            cd ${{ secrets.PROJECT_PATH }}
            docker compose down
            docker pull ghcr.io/${{ github.repository_owner }}/blog-frontend:latest
            docker compose up -d
            docker image prune -f
