name: Docker Build & Push

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  docker_build:
    runs-on: ubuntu-latest
    if: success() # Only run this job if the build job was successful

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN  }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-blog-frontend:latest